### PR TITLE
Week 1 Quiz Submission from lceballos-stat6250

### PR DESCRIPTION
**Pull request by lceballos-stat6863**
Quiz 1.

### CODE REVIEW

**Review by prof-lankham — CHANGES_REQUESTED** [review]
Existing content should *NOT* be deleted.

**Review by prof-lankham — CHANGES_REQUESTED** [review]
Question/answer formatting should be followed exactly

**Comment by lceballos-stat6863** [comment]
Changes made

**Comment by lceballos-stat6250** [comment]
Changes made: 
Solved conflicts.

**Comment by lceballos-stat6863** [comment]
conflicts resolved

**Comment by lceballos-stat6250** [comment]
@prof-lankham 
Please approve this push.

Thanks

**Comment by lceballos-stat6863** [comment]
@prof-lankham
I think this should finally get all the conflicts resolved. Please approve this push.

Thanks

**Pull request merged**
