### PR TITLE
Week 2 Quiz submission from tbishaw-stat6250

### PR DESCRIPTION
**Pull request by tbishaw-stat6250**

### CODE REVIEW

**Review by tbishaw-stat6250 — COMMENTED** [review]
Week 2 Quiz submission from tbishaw-stat6250 (updated)

**Review by prof-lankham — CHANGES_REQUESTED** [review]
Question/Answer format incorrect; please update to match instructions, with a dash, then a space, and then the word Questions or Answer

**Comment by prof-lankham** [comment]
Please make required changed and DM me in Slack with PR URL when ready for re-evaluation.

**Review by tbishaw-stat6250 — COMMENTED** [review]
Updated formatting.

**Comment by prof-lankham** [comment]
This PR renames a file and is being closed; please open a new PR after following all specified, and DM me in Slack with PR URL when ready for re-evaluation.

**Pull request closed without merging**
