### PR TITLE
Week 2 Quiz Submission from sbagdi-stat6250

### PR DESCRIPTION
**Pull request by SurbhiBagdi**

### CODE REVIEW

**Review by prof-lankham — CHANGES_REQUESTED** [review]
Title incorrect; question formatting incorrect; please update PR to match provided instructions

**Comment by prof-lankham** [comment]
Please make required changed and DM me in Slack with PR URL when ready for re-evaluation.

**Comment by SurbhiBagdi** [comment]
Professor. Have I edited the pull request correctly?

**Comment by prof-lankham** [comment]
Resubmission deadline passed; PR closed; please DM me in Slack to discuss options

**Pull request closed without merging**
